#! /usr/bin/bash

# Link the directories in .config
cfgpath="$HOME/.config"

for dir in .config/*/; do
  n=$(basename "$dir")  
  echo "$n"

  target="$cfgpath/$n"
  echo "Target: $target"

  if [ -d "$target" ]; then
    echo "$target is an existing directory. Deleting"
    rm -rf $target
  fi
  src="$HOME/dotfiles/.config/$n"
  echo "Linking"
  echo "$src -> $target"
  ln -sf "$src" "$target"
done

# Link other misc items
ln -sf "$HOME/dotfiles/desktopbg.png" > "$HOME/desktopbg.png"
