theme = "spectrumnobg"

[keys.normal]
"g" = { "v" = ["vsplit", "jump_view_up", "goto_definition"] }

[keys.normal.space]
"h" = "jump_view_left"
"H" = "swap_view_left"
"l" = "jump_view_right"
"L" = "swap_view_right"
"q" = "wclose"
"o" = "wonly"
"=" = ["goto_file_start", "select_mode", "goto_file_end", "format_selections"]

[editor.file-picker]
hidden = false
git-ignore = false

[editor]
color-modes = true
