format = """
$directory\
$git_branch\
$git_status\
\n$character
"""

[username]
show_always = true

[directory]
truncate_to_repo = false

[git_status]
style = 'yellow'
# ahead = '⇡${count}'
# diverged = '⇕⇡${ahead_count}⇣${behind_count}'
# behind = '⇣${count}'
format = '([\[$all_status$ahead_behind\]]($style) )'
